### ISSUE TITLE
HOME_PRINTER

### ISSUE THREAD

**Issue by noobydp** [vladbabii/klippy-cnc#10]
Howdy, I'm struggling to understand some parts of these macros, I have them loaded properly and customised m3 and m4 to work with my setup.

I'm currently stuck with homing. I see the custom macro kcnc_home_machine and I uncommented as below:
# Home Machine Axis
[gcode_macro kcnc_home_machine]
gcode:
  G990028

But the machine doesnt respond to this macro at all.

**Comment by robwaldhauser** [comment]
I'd love some explanation of how this works. Currently trying to read through all the macros and track their actions back to get a better understanding. It would really be beneficial if the author would share just a bit more about how to use these macros, maybe even a workflow that should be followed.

**Comment by noobydp** [comment]
I ended up abandoning this and wrote my own macros. 
They're tailored to my machine but should be easier to understand. 

The documentation is out of date.

https://github.com/noobydp/CNC-Macros

**Comment by robwaldhauser** [comment]
> I ended up abandoning this and wrote my own macros. They're tailored to my machine but should be easier to understand.
> 
> The documentation is out of date.
> 
> https://github.com/noobydp/CNC-Macros

Oh awesome, I actually did the same last night, decided I'm done trying to make something work where the author isn't responding. I'll check out your work, should make my life a lot easier. Happy to contribute some ideas as well if I have any to share and you're open for it. Cheers!

**Comment by noobydp** [comment]
Yeah I don't mind :) 
I'll work on the instructions tomorrow.
